### PR TITLE
fix(2288): fix sonarqube setting

### PR DESCRIPTION
**Pull request by klu909**
## Context

Sonarqube setting was broken and doesn't have test execution setting
## Objective

Fix sonarqube setting
## References

https://github.com/screwdriver-cd/screwdriver/issues/2288
## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by jithine — APPROVED** [review]

**Review by jithine — COMMENTED** [review]
why is this showing 0% coverage ? https://cd.screwdriver.cd/pipelines/202/builds/665161

**Comment by klu909** [comment]
> why is this showing 0% coverage ? https://cd.screwdriver.cd/pipelines/202/builds/665161

seems like file generate by nyc is empty for this repo

**Comment by jithine** [comment]
> seems like file generate by nyc is empty for this repo
is that same locally as well ?

**Comment by klu909** [comment]
> > seems like file generate by nyc is empty for this repo
> > is that same locally as well ?

yeah

**Review by jithine — APPROVED** [review]

**Pull request merged**
